# Generated by Django 5.0.1 on 2025-12-30 02:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0005_asset_sector_asset_subsection"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="active_power_kw",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Potência ativa em kW (P = S × FP)",
                max_digits=10,
                null=True,
                verbose_name="Potência Ativa (kW)",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="apparent_power_kva",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Potência aparente em kVA (S = √3 × V × I)",
                max_digits=10,
                null=True,
                verbose_name="Potência Aparente (kVA)",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="capacity",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Capacidade térmica do equipamento",
                max_digits=12,
                null=True,
                verbose_name="Capacidade",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="capacity_unit",
            field=models.CharField(
                choices=[
                    ("BTU", "BTUs"),
                    ("TR", "TR (Toneladas de Refrigeração)"),
                    ("KCAL", "kcal/h"),
                    ("KW", "kW (Térmico)"),
                ],
                default="BTU",
                help_text="Unidade de medida da capacidade térmica",
                max_length=10,
                verbose_name="Unidade de Capacidade",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="criticality",
            field=models.CharField(
                choices=[
                    ("BAIXA", "Baixa"),
                    ("MEDIA", "Média"),
                    ("ALTA", "Alta"),
                    ("CRITICA", "Crítica"),
                ],
                default="MEDIA",
                help_text="Nível de criticidade operacional do equipamento",
                max_length=10,
                verbose_name="Criticidade",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="nominal_current",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Corrente nominal de operação em Amperes",
                max_digits=10,
                null=True,
                verbose_name="Corrente Nominal (A)",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="nominal_voltage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Tensão nominal de operação em Volts",
                max_digits=10,
                null=True,
                verbose_name="Tensão Nominal (V)",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="patrimony_number",
            field=models.CharField(
                blank=True,
                help_text="Número de patrimônio interno da empresa",
                max_length=100,
                verbose_name="Número de Patrimônio",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="phases",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Monofásico"), (3, "Trifásico")],
                default=3,
                help_text="Número de fases do equipamento",
                verbose_name="Fases",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="power_factor",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Fator de potência (cos φ) - valor entre 0 e 1",
                max_digits=4,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
                verbose_name="Fator de Potência",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="reactive_power_kvar",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Potência reativa em kVAr (Q = √(S² - P²))",
                max_digits=10,
                null=True,
                verbose_name="Potência Reativa (kVAr)",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="refrigerant",
            field=models.CharField(
                blank=True,
                help_text="Tipo de fluido refrigerante (ex: R-410A, R-134a)",
                max_length=50,
                verbose_name="Fluido Refrigerante",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="warranty_expiry",
            field=models.DateField(
                blank=True,
                help_text="Data de expiração da garantia do equipamento",
                null=True,
                verbose_name="Fim da Garantia",
            ),
        ),
    ]
