# Generated by Django 5.0.1 on 2025-12-30 02:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0006_add_electrical_specs_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="phases",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Monofásico"), (2, "Bifásico"), (3, "Trifásico")],
                default=3,
                help_text="Número de fases do equipamento",
                verbose_name="Fases",
            ),
        ),
    ]
