# Generated by Django 5.0.1 on 2026-01-06 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0007_add_bifasico_option"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Código único do tipo de ativo (ex: FANCOIL_PISO)",
                        max_length=50,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nome exibível do tipo de ativo",
                        max_length=100,
                        verbose_name="Nome",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descrição opcional do tipo de ativo",
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        help_text="Se verdadeiro, é um tipo padrão do sistema e não pode ser excluído",
                        verbose_name="Tipo do Sistema",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tipo de Ativo",
                "verbose_name_plural": "Tipos de Ativo",
                "db_table": "asset_types",
                "ordering": ["name"],
            },
        ),
    ]
