# Generated by Django 5.0.1 on 2026-01-06 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0009_seed_system_asset_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="asset_type",
            field=models.CharField(
                db_index=True,
                help_text="Código do tipo de equipamento (deve existir na tabela AssetType)",
                max_length=50,
                verbose_name="Tipo de Equipamento",
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="asset_type_other",
            field=models.CharField(
                blank=True,
                help_text="Especificar quando asset_type = OTHER (legado)",
                max_length=200,
                verbose_name="Outro Tipo (texto livre)",
            ),
        ),
    ]
