# Generated by Django 5.0.1 on 2025-12-28 00:00

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0005_asset_sector_asset_subsection"),
        ("cmms", "0006_add_checklist_category"),
        ("trakledger", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CostTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True,
                        help_text="Chave única para evitar duplicação (ex: wo:uuid:labor)",
                        max_length=255,
                        null=True,
                        verbose_name="Chave de Idempotência",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("labor", "Mão de Obra"),
                            ("parts", "Peças/Materiais"),
                            ("third_party", "Terceiros"),
                            ("energy", "Energia"),
                            ("adjustment", "Ajuste"),
                            ("other", "Outros"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Transação",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("preventive", "Manutenção Preventiva"),
                            ("corrective", "Manutenção Corretiva"),
                            ("predictive", "Manutenção Preditiva"),
                            ("improvement", "Melhorias"),
                            ("contracts", "Contratos"),
                            ("parts", "Peças e Materiais"),
                            ("energy", "Energia"),
                            ("other", "Outros"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor da transação (positivo = custo, negativo = crédito)",
                        max_digits=15,
                        verbose_name="Valor",
                    ),
                ),
                (
                    "currency",
                    models.CharField(default="BRL", max_length=3, verbose_name="Moeda"),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        help_text="Data em que o custo ocorreu",
                        verbose_name="Data da Ocorrência",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descrição detalhada da transação",
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "meta",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Dados adicionais (ex: breakdown de horas, itens)",
                        verbose_name="Metadados",
                    ),
                ),
                (
                    "vendor_id",
                    models.UUIDField(
                        blank=True,
                        help_text="ID do fornecedor (para terceiros/contratos)",
                        null=True,
                        verbose_name="Fornecedor ID",
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False,
                        help_text="Transação bloqueada para edição (período fechado)",
                        verbose_name="Bloqueado",
                    ),
                ),
                (
                    "locked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Bloqueado em"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cost_transactions",
                        to="assets.asset",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "cost_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="trakledger.costcenter",
                        verbose_name="Centro de Custo",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_cost_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "locked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locked_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Bloqueado por",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cost_transactions",
                        to="cmms.workorder",
                        verbose_name="Ordem de Serviço",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transação de Custo",
                "verbose_name_plural": "Transações de Custo",
                "ordering": ["-occurred_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LedgerAdjustment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "adjustment_type",
                    models.CharField(
                        choices=[
                            ("correction", "Correção de Valor"),
                            ("reclassification", "Reclassificação"),
                            ("reversal", "Estorno"),
                            ("other", "Outro"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Ajuste",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="Justificativa para o ajuste (obrigatório)",
                        verbose_name="Motivo",
                    ),
                ),
                (
                    "original_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Valor da transação antes do ajuste",
                        max_digits=15,
                        null=True,
                        verbose_name="Valor Original",
                    ),
                ),
                (
                    "adjustment_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor do ajuste (positivo ou negativo)",
                        max_digits=15,
                        verbose_name="Valor do Ajuste",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        default=True,
                        help_text="Se requer aprovação, iniciar como False",
                        verbose_name="Aprovado",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Aprovado em"
                    ),
                ),
                (
                    "adjustment_transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adjustment_record",
                        to="trakledger.costtransaction",
                        verbose_name="Transação de Ajuste",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_adjustments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aprovado por",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_adjustments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "original_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adjustments",
                        to="trakledger.costtransaction",
                        verbose_name="Transação Original",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ajuste de Ledger",
                "verbose_name_plural": "Ajustes de Ledger",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="costtransaction",
            index=models.Index(
                fields=["idempotency_key"], name="finance_ctx_idemp_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="costtransaction",
            index=models.Index(
                fields=["transaction_type"], name="finance_ctx_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="costtransaction",
            index=models.Index(fields=["category"], name="finance_ctx_cat_idx"),
        ),
        migrations.AddIndex(
            model_name="costtransaction",
            index=models.Index(fields=["occurred_at"], name="finance_ctx_occurred_idx"),
        ),
        migrations.AddIndex(
            model_name="costtransaction",
            index=models.Index(fields=["cost_center"], name="finance_ctx_cc_idx"),
        ),
        migrations.AddIndex(
            model_name="costtransaction",
            index=models.Index(fields=["work_order"], name="finance_ctx_wo_idx"),
        ),
        migrations.AddIndex(
            model_name="costtransaction",
            index=models.Index(fields=["asset"], name="finance_ctx_asset_idx"),
        ),
        migrations.AddIndex(
            model_name="costtransaction",
            index=models.Index(fields=["is_locked"], name="finance_ctx_locked_idx"),
        ),
        migrations.AddIndex(
            model_name="costtransaction",
            index=models.Index(
                fields=["cost_center", "category", "occurred_at"],
                name="finance_ctx_summary_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="costtransaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key__isnull", False)),
                fields=("idempotency_key",),
                name="finance_costtx_unique_idempotency",
            ),
        ),
        migrations.AddIndex(
            model_name="ledgeradjustment",
            index=models.Index(
                fields=["original_transaction"], name="finance_adj_orig_tx_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ledgeradjustment",
            index=models.Index(fields=["adjustment_type"], name="finance_adj_type_idx"),
        ),
        migrations.AddIndex(
            model_name="ledgeradjustment",
            index=models.Index(fields=["created_at"], name="finance_adj_created_idx"),
        ),
        migrations.AddIndex(
            model_name="ledgeradjustment",
            index=models.Index(fields=["is_approved"], name="finance_adj_approved_idx"),
        ),
    ]
