# Generated by Django 5.0.1 on 2025-12-29 02:14

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cmms", "0009_add_commitment_model"),
        ("trakledger", "0002_ledger_costtransaction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Commitment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "budget_month",
                    models.DateField(
                        help_text="Primeiro dia do mês (ex: 2024-01-01)",
                        verbose_name="Mês do Orçamento",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor comprometido",
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Valor",
                    ),
                ),
                (
                    "currency",
                    models.CharField(default="BRL", max_length=3, verbose_name="Moeda"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("preventive", "Manutenção Preventiva"),
                            ("corrective", "Manutenção Corretiva"),
                            ("predictive", "Manutenção Preditiva"),
                            ("improvement", "Melhorias"),
                            ("contracts", "Contratos"),
                            ("parts", "Peças e Materiais"),
                            ("energy", "Energia"),
                            ("other", "Outros"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Rascunho"),
                            ("submitted", "Submetido"),
                            ("approved", "Aprovado"),
                            ("rejected", "Rejeitado"),
                            ("cancelled", "Cancelado"),
                            ("realized", "Realizado"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Descrição do compromisso", verbose_name="Descrição"
                    ),
                ),
                (
                    "vendor_name",
                    models.CharField(
                        blank=True,
                        help_text="Nome do fornecedor (se aplicável)",
                        max_length=200,
                        verbose_name="Nome do Fornecedor",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Aprovado em"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="Motivo da Rejeição"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_commitments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aprovado por",
                    ),
                ),
                (
                    "cost_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commitments",
                        to="trakledger.costcenter",
                        verbose_name="Centro de Custo",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_commitments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commitments",
                        to="cmms.workorder",
                        verbose_name="Ordem de Serviço",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compromisso",
                "verbose_name_plural": "Compromissos",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["cost_center"], name="finance_commit_cc_idx"),
                    models.Index(
                        fields=["budget_month"], name="finance_commit_month_idx"
                    ),
                    models.Index(fields=["status"], name="finance_commit_status_idx"),
                    models.Index(fields=["category"], name="finance_commit_cat_idx"),
                    models.Index(fields=["work_order"], name="finance_commit_wo_idx"),
                    models.Index(
                        fields=["cost_center", "budget_month", "status"],
                        name="finance_commit_summary_idx",
                    ),
                ],
            },
        ),
    ]
