# Generated by Django 5.0.1 on 2025-12-29 15:39

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0005_asset_sector_asset_subsection"),
        ("cmms", "0009_add_commitment_model"),
        ("trakledger", "0004_add_savings_event_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EnergyTariff",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nome descritivo (ex: CEMIG B3 Comercial)",
                        max_length=200,
                        verbose_name="Nome da Tarifa",
                    ),
                ),
                (
                    "distributor",
                    models.CharField(
                        help_text="Nome da distribuidora (ex: CEMIG, CPFL, Light)",
                        max_length=100,
                        verbose_name="Distribuidora",
                    ),
                ),
                (
                    "tariff_class",
                    models.CharField(
                        blank=True,
                        help_text="Classe da tarifa (ex: B1, B3, A4)",
                        max_length=50,
                        verbose_name="Classe Tarifária",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "rate_off_peak",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Valor por kWh no horário fora de ponta",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.000000")
                            )
                        ],
                        verbose_name="Tarifa Fora Ponta (R$/kWh)",
                    ),
                ),
                (
                    "rate_peak",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Valor por kWh no horário de ponta",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.000000")
                            )
                        ],
                        verbose_name="Tarifa Ponta (R$/kWh)",
                    ),
                ),
                (
                    "rate_intermediate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Valor por kWh no horário intermediário (se aplicável)",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.000000")
                            )
                        ],
                        verbose_name="Tarifa Intermediária (R$/kWh)",
                    ),
                ),
                (
                    "peak_start",
                    models.TimeField(
                        help_text="Hora de início do horário de ponta (ex: 18:00)",
                        verbose_name="Início Horário Ponta",
                    ),
                ),
                (
                    "peak_end",
                    models.TimeField(
                        help_text="Hora de fim do horário de ponta (ex: 21:00)",
                        verbose_name="Fim Horário Ponta",
                    ),
                ),
                (
                    "flag_verde",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0.000000"),
                        help_text="Acréscimo bandeira verde (normalmente 0)",
                        max_digits=10,
                        verbose_name="Acréscimo Verde (R$/kWh)",
                    ),
                ),
                (
                    "flag_amarela",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0.000000"),
                        help_text="Acréscimo bandeira amarela",
                        max_digits=10,
                        verbose_name="Acréscimo Amarela (R$/kWh)",
                    ),
                ),
                (
                    "flag_vermelha_1",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0.000000"),
                        help_text="Acréscimo bandeira vermelha patamar 1",
                        max_digits=10,
                        verbose_name="Acréscimo Vermelha P1 (R$/kWh)",
                    ),
                ),
                (
                    "flag_vermelha_2",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0.000000"),
                        help_text="Acréscimo bandeira vermelha patamar 2",
                        max_digits=10,
                        verbose_name="Acréscimo Vermelha P2 (R$/kWh)",
                    ),
                ),
                (
                    "effective_from",
                    models.DateField(
                        help_text="Data de início da vigência desta tarifa",
                        verbose_name="Vigência Início",
                    ),
                ),
                (
                    "effective_to",
                    models.DateField(
                        blank=True,
                        help_text="Data de fim da vigência (vazio = vigente)",
                        null=True,
                        verbose_name="Vigência Fim",
                    ),
                ),
                (
                    "currency",
                    models.CharField(default="BRL", max_length=3, verbose_name="Moeda"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativa")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_energy_tariffs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarifa de Energia",
                "verbose_name_plural": "Tarifas de Energia",
                "ordering": ["-effective_from", "distributor"],
            },
        ),
        migrations.CreateModel(
            name="EnergyReading",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reading_date",
                    models.DateField(
                        help_text="Data do consumo registrado",
                        verbose_name="Data da Leitura",
                    ),
                ),
                (
                    "kwh_total",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Consumo total em quilowatt-hora",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.000"))
                        ],
                        verbose_name="Consumo Total (kWh)",
                    ),
                ),
                (
                    "kwh_peak",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.000"),
                        help_text="Consumo no horário de ponta",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.000"))
                        ],
                        verbose_name="Consumo Ponta (kWh)",
                    ),
                ),
                (
                    "kwh_off_peak",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.000"),
                        help_text="Consumo no horário fora de ponta",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.000"))
                        ],
                        verbose_name="Consumo Fora Ponta (kWh)",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("meter", "Medidor"),
                            ("estimate", "Estimativa"),
                            ("telemetry", "Telemetria IoT"),
                            ("manual", "Entrada Manual"),
                        ],
                        default="manual",
                        max_length=20,
                        verbose_name="Origem",
                    ),
                ),
                (
                    "bandeira",
                    models.CharField(
                        choices=[
                            ("verde", "Verde (sem acréscimo)"),
                            ("amarela", "Amarela"),
                            ("vermelha_1", "Vermelha Patamar 1"),
                            ("vermelha_2", "Vermelha Patamar 2"),
                        ],
                        default="verde",
                        max_length=20,
                        verbose_name="Bandeira Tarifária",
                    ),
                ),
                (
                    "calculated_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Custo calculado automaticamente",
                        max_digits=12,
                        null=True,
                        verbose_name="Custo Calculado (R$)",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                (
                    "meta",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Dados adicionais (ex: leitura anterior, fator de demanda)",
                        verbose_name="Metadados",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="energy_readings",
                        to="assets.asset",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "cost_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="energy_readings",
                        to="trakledger.costcenter",
                        verbose_name="Centro de Custo",
                    ),
                ),
                (
                    "cost_transaction",
                    models.ForeignKey(
                        blank=True,
                        help_text="Transação no ledger (gerada automaticamente)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="energy_readings",
                        to="trakledger.costtransaction",
                        verbose_name="Transação de Custo",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_energy_readings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "tariff",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tarifa usada para cálculo (auto-preenchido se vazio)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="readings",
                        to="trakledger.energytariff",
                        verbose_name="Tarifa Aplicada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leitura de Energia",
                "verbose_name_plural": "Leituras de Energia",
                "ordering": ["-reading_date", "asset"],
            },
        ),
        migrations.CreateModel(
            name="RiskSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "snapshot_date",
                    models.DateField(
                        help_text="Data em que o risco foi calculado",
                        verbose_name="Data do Snapshot",
                    ),
                ),
                (
                    "failure_probability",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Probabilidade de falha (0-1, ex: 0.15 = 15%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0000")),
                            django.core.validators.MaxValueValidator(Decimal("1.0000")),
                        ],
                        verbose_name="Probabilidade de Falha",
                    ),
                ),
                (
                    "mtbf_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Tempo médio entre falhas em dias",
                        null=True,
                        verbose_name="MTBF (dias)",
                    ),
                ),
                (
                    "estimated_repair_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Custo estimado para reparar em caso de falha",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Custo Estimado de Reparo (R$)",
                    ),
                ),
                (
                    "estimated_downtime_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Tempo estimado de parada em horas",
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Downtime Estimado (horas)",
                    ),
                ),
                (
                    "downtime_cost_per_hour",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Custo por hora de parada",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Custo Downtime (R$/hora)",
                    ),
                ),
                (
                    "downtime_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="= downtime_hours × cost_per_hour",
                        max_digits=12,
                        verbose_name="Custo Total Downtime (R$)",
                    ),
                ),
                (
                    "total_impact_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="= repair_cost + downtime_cost",
                        max_digits=12,
                        verbose_name="Impacto Total (R$)",
                    ),
                ),
                (
                    "risk_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="= probability × total_impact",
                        max_digits=12,
                        verbose_name="Risk Score (R$)",
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Baixo"),
                            ("medium", "Médio"),
                            ("high", "Alto"),
                            ("critical", "Crítico"),
                        ],
                        default="low",
                        max_length=20,
                        verbose_name="Nível de Risco",
                    ),
                ),
                (
                    "data_source",
                    models.CharField(
                        blank=True,
                        help_text="Origem dos dados (ex: histórico, telemetria, especialista)",
                        max_length=100,
                        verbose_name="Fonte dos Dados",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                (
                    "meta",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Dados adicionais (ex: fatores considerados, histórico)",
                        verbose_name="Metadados",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_snapshots",
                        to="assets.asset",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "cost_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="risk_snapshots",
                        to="trakledger.costcenter",
                        verbose_name="Centro de Custo",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_risk_snapshots",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Snapshot de Risco",
                "verbose_name_plural": "Snapshots de Risco",
                "ordering": ["-snapshot_date", "-risk_score"],
            },
        ),
        migrations.CreateModel(
            name="Baseline",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nome descritivo (ex: Retrofit Chiller #1 - Energia)",
                        max_length=200,
                        verbose_name="Nome",
                    ),
                ),
                (
                    "baseline_type",
                    models.CharField(
                        choices=[
                            ("energy", "Consumo de Energia"),
                            ("runtime", "Tempo de Operação"),
                            ("maintenance", "Frequência de Manutenção"),
                            ("performance", "Desempenho"),
                            ("custom", "Personalizado"),
                        ],
                        default="energy",
                        max_length=20,
                        verbose_name="Tipo de Baseline",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Descrição da Intervenção"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("collecting_before", "Coletando Dados Antes"),
                            ("intervention", "Em Intervenção"),
                            ("collecting_after", "Coletando Dados Depois"),
                            ("calculated", "Economia Calculada"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="collecting_before",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                (
                    "before_start",
                    models.DateField(
                        help_text="Início da coleta de dados antes da intervenção",
                        verbose_name="Início Período Antes",
                    ),
                ),
                (
                    "before_end",
                    models.DateField(
                        blank=True,
                        help_text="Fim da coleta de dados antes da intervenção",
                        null=True,
                        verbose_name="Fim Período Antes",
                    ),
                ),
                (
                    "before_avg_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Valor médio no período antes (ex: kWh/dia)",
                        max_digits=12,
                        null=True,
                        verbose_name="Valor Médio Antes",
                    ),
                ),
                (
                    "before_total_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Valor total no período antes",
                        max_digits=15,
                        null=True,
                        verbose_name="Valor Total Antes",
                    ),
                ),
                (
                    "before_days",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Dias Coletados Antes"
                    ),
                ),
                (
                    "before_data_points",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Pontos de Dados Antes"
                    ),
                ),
                (
                    "intervention_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data da Intervenção"
                    ),
                ),
                (
                    "after_start",
                    models.DateField(
                        blank=True,
                        help_text="Início da coleta de dados depois da intervenção",
                        null=True,
                        verbose_name="Início Período Depois",
                    ),
                ),
                (
                    "after_end",
                    models.DateField(
                        blank=True,
                        help_text="Fim da coleta de dados depois da intervenção",
                        null=True,
                        verbose_name="Fim Período Depois",
                    ),
                ),
                (
                    "after_avg_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Valor médio no período depois (ex: kWh/dia)",
                        max_digits=12,
                        null=True,
                        verbose_name="Valor Médio Depois",
                    ),
                ),
                (
                    "after_total_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Valor total no período depois",
                        max_digits=15,
                        null=True,
                        verbose_name="Valor Total Depois",
                    ),
                ),
                (
                    "after_days",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Dias Coletados Depois"
                    ),
                ),
                (
                    "after_data_points",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Pontos de Dados Depois"
                    ),
                ),
                (
                    "savings_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Economia calculada por período (ex: kWh/dia)",
                        max_digits=12,
                        null=True,
                        verbose_name="Economia por Período",
                    ),
                ),
                (
                    "savings_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Percentual de economia",
                        max_digits=6,
                        null=True,
                        verbose_name="Economia (%)",
                    ),
                ),
                (
                    "savings_annual_estimate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Projeção de economia anual em reais",
                        max_digits=15,
                        null=True,
                        verbose_name="Economia Anual Estimada (R$)",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        default="kWh",
                        help_text="Unidade de medida (ex: kWh, horas, R$)",
                        max_length=20,
                        verbose_name="Unidade",
                    ),
                ),
                (
                    "meta",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Dados adicionais (ex: configurações, parâmetros)",
                        verbose_name="Metadados",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="baselines",
                        to="assets.asset",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "cost_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="baselines",
                        to="trakledger.costcenter",
                        verbose_name="Centro de Custo",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_baselines",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "savings_event",
                    models.ForeignKey(
                        blank=True,
                        help_text="SavingsEvent gerado automaticamente",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="baselines",
                        to="trakledger.savingsevent",
                        verbose_name="Evento de Economia",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        blank=True,
                        help_text="OS da intervenção (se aplicável)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="baselines",
                        to="cmms.workorder",
                        verbose_name="Ordem de Serviço",
                    ),
                ),
            ],
            options={
                "verbose_name": "Baseline",
                "verbose_name_plural": "Baselines",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["asset"], name="trakledger_baseline_asset_idx"),
                    models.Index(
                        fields=["cost_center"], name="trakledger_baseline_cc_idx"
                    ),
                    models.Index(fields=["status"], name="trakledger_baseline_status_idx"),
                    models.Index(
                        fields=["baseline_type"], name="trakledger_baseline_type_idx"
                    ),
                    models.Index(fields=["work_order"], name="trakledger_baseline_wo_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="energytariff",
            index=models.Index(
                fields=["distributor"], name="trakledger_etariff_distrib_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="energytariff",
            index=models.Index(
                fields=["tariff_class"], name="trakledger_etariff_class_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="energytariff",
            index=models.Index(
                fields=["effective_from", "effective_to"],
                name="trakledger_etariff_vig_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="energytariff",
            index=models.Index(fields=["is_active"], name="trakledger_etariff_active_idx"),
        ),
        migrations.AddIndex(
            model_name="energyreading",
            index=models.Index(
                fields=["asset", "reading_date"], name="trakledger_ereading_asset_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="energyreading",
            index=models.Index(
                fields=["reading_date"], name="trakledger_ereading_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="energyreading",
            index=models.Index(fields=["cost_center"], name="trakledger_ereading_cc_idx"),
        ),
        migrations.AddIndex(
            model_name="energyreading",
            index=models.Index(fields=["source"], name="trakledger_ereading_source_idx"),
        ),
        migrations.AddConstraint(
            model_name="energyreading",
            constraint=models.UniqueConstraint(
                fields=("asset", "reading_date"),
                name="trakledger_ereading_unique_asset_date",
            ),
        ),
        migrations.AddIndex(
            model_name="risksnapshot",
            index=models.Index(
                fields=["asset", "snapshot_date"], name="trakledger_risk_asset_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="risksnapshot",
            index=models.Index(fields=["snapshot_date"], name="trakledger_risk_date_idx"),
        ),
        migrations.AddIndex(
            model_name="risksnapshot",
            index=models.Index(fields=["cost_center"], name="trakledger_risk_cc_idx"),
        ),
        migrations.AddIndex(
            model_name="risksnapshot",
            index=models.Index(fields=["risk_level"], name="trakledger_risk_level_idx"),
        ),
        migrations.AddIndex(
            model_name="risksnapshot",
            index=models.Index(fields=["risk_score"], name="trakledger_risk_score_idx"),
        ),
        migrations.AddConstraint(
            model_name="risksnapshot",
            constraint=models.UniqueConstraint(
                fields=("asset", "snapshot_date"),
                name="trakledger_risksnapshot_unique_asset_date",
            ),
        ),
    ]
