# Generated by Django 5.0.1 on 2026-01-07 23:34
# Modified to use conditional index renaming for fresh databases

from django.conf import settings
from django.db import migrations, models


def rename_index_if_exists(apps, schema_editor):
    """Rename old finance_* indexes to trakledger_* if they exist."""
    renames = [
        # Commitment indexes
        ("finance_commit_cc_idx", "trakledger_commit_cc_idx"),
        ("finance_commit_month_idx", "trakledger_commit_month_idx"),
        ("finance_commit_status_idx", "trakledger_commit_status_idx"),
        ("finance_commit_cat_idx", "trakledger_commit_cat_idx"),
        ("finance_commit_wo_idx", "trakledger_commit_wo_idx"),
        ("finance_commit_summary_idx", "trakledger_commit_summary_idx"),
        # CostTransaction indexes
        ("finance_ctx_idemp_idx", "trakledger_ctx_idemp_idx"),
        ("finance_ctx_type_idx", "trakledger_ctx_type_idx"),
        ("finance_ctx_cat_idx", "trakledger_ctx_cat_idx"),
        ("finance_ctx_occurred_idx", "trakledger_ctx_occurred_idx"),
        ("finance_ctx_cc_idx", "trakledger_ctx_cc_idx"),
        ("finance_ctx_wo_idx", "trakledger_ctx_wo_idx"),
        ("finance_ctx_asset_idx", "trakledger_ctx_asset_idx"),
        ("finance_ctx_locked_idx", "trakledger_ctx_locked_idx"),
        ("finance_ctx_summary_idx", "trakledger_ctx_summary_idx"),
        # LedgerAdjustment indexes
        ("finance_adj_orig_tx_idx", "trakledger_adj_orig_tx_idx"),
        ("finance_adj_type_idx", "trakledger_adj_type_idx"),
        ("finance_adj_created_idx", "trakledger_adj_created_idx"),
        ("finance_adj_approved_idx", "trakledger_adj_approved_idx"),
        # SavingsEvent indexes
        ("finance_savings_cc_idx", "tl_savings_cc_idx"),
        ("finance_savings_type_idx", "tl_savings_type_idx"),
        ("finance_savings_occurred_idx", "tl_savings_occurred_idx"),
        ("finance_savings_asset_idx", "tl_savings_asset_idx"),
        ("finance_savings_wo_idx", "tl_savings_wo_idx"),
        ("finance_savings_summary_idx", "tl_savings_summary_idx"),
    ]
    
    with schema_editor.connection.cursor() as cursor:
        for old_name, new_name in renames:
            # Check if old index exists before renaming
            cursor.execute(
                """
                SELECT 1 FROM pg_indexes 
                WHERE indexname = %s
                """,
                [old_name]
            )
            if cursor.fetchone():
                cursor.execute(
                    f'ALTER INDEX IF EXISTS "{old_name}" RENAME TO "{new_name}"'
                )


def remove_constraint_if_exists(apps, schema_editor):
    """Remove old constraints if they exist."""
    constraints = [
        ("trakledger_budgetenvelope", "trakledger_envelope_unique_plan_cc_cat"),
        ("trakledger_budgetmonth", "trakledger_budgetmonth_unique_env_month"),
        ("trakledger_budgetplan", "trakledger_budgetplan_unique_code"),
        ("trakledger_costcenter", "trakledger_costcenter_unique_code"),
        ("trakledger_costtransaction", "finance_costtx_unique_idempotency"),
        ("trakledger_energyreading", "trakledger_ereading_unique_asset_date"),
        ("trakledger_risksnapshot", "trakledger_risksnapshot_unique_asset_date"),
    ]
    
    with schema_editor.connection.cursor() as cursor:
        for table_name, constraint_name in constraints:
            cursor.execute(
                """
                SELECT 1 FROM information_schema.table_constraints 
                WHERE constraint_name = %s AND table_name = %s
                """,
                [constraint_name, table_name]
            )
            if cursor.fetchone():
                cursor.execute(
                    f'ALTER TABLE "{table_name}" DROP CONSTRAINT IF EXISTS "{constraint_name}"'
                )


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0010_remove_asset_type_choices"),
        ("cmms", "0011_add_part_usage_source"),
        ("trakledger", "0007_rename_finance_to_trakledger"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Remove old constraints (conditionally)
        migrations.RunPython(remove_constraint_if_exists, migrations.RunPython.noop),
        
        # Rename indexes (conditionally)
        migrations.RunPython(rename_index_if_exists, migrations.RunPython.noop),
        
        # Add new constraints (these are idempotent - Django handles duplicates)
        migrations.AddConstraint(
            model_name="budgetenvelope",
            constraint=models.UniqueConstraint(
                fields=("budget_plan", "cost_center", "category"),
                name="tl_env_uniq_plan_cc_cat",
            ),
        ),
        migrations.AddConstraint(
            model_name="budgetmonth",
            constraint=models.UniqueConstraint(
                fields=("envelope", "month"), name="tl_bm_uniq_env_month"
            ),
        ),
        migrations.AddConstraint(
            model_name="budgetplan",
            constraint=models.UniqueConstraint(
                fields=("code",), name="tl_bp_unique_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="costcenter",
            constraint=models.UniqueConstraint(
                fields=("code",), name="tl_cc_unique_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="costtransaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key__isnull", False)),
                fields=("idempotency_key",),
                name="tl_ctx_uniq_idempotency",
            ),
        ),
        migrations.AddConstraint(
            model_name="energyreading",
            constraint=models.UniqueConstraint(
                fields=("asset", "reading_date"), name="tl_eread_uniq_asset_date"
            ),
        ),
        migrations.AddConstraint(
            model_name="risksnapshot",
            constraint=models.UniqueConstraint(
                fields=("asset", "snapshot_date"), name="tl_risk_uniq_asset_date"
            ),
        ),
    ]
