# Generated by Django 5.0.1 on 2026-01-07 23:34
# This migration is now a NO-OP as 0007 already handles all renaming correctly
# using IF EXISTS syntax which is safe for both fresh and existing databases.

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    """
    This migration was originally intended to fix constraint/index naming,
    but migration 0007 already handles everything correctly with IF EXISTS.
    
    Keeping this as a no-op to preserve migration history for existing databases.
    """

    dependencies = [
        ("assets", "0010_remove_asset_type_choices"),
        ("cmms", "0011_add_part_usage_source"),
        ("trakledger", "0007_rename_finance_to_trakledger"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # No-op - everything is handled in 0007
    ]
