# Generated by Django 5.2.8 on 2026-01-12 00:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0010_remove_asset_type_choices"),
        ("cmms", "0014_alter_partusage_inventory_movement_id"),
        ("trakledger", "0008_rename_indexes_to_trakledger"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="budgetenvelope",
            name="trakledger_envelope_unique_plan_cc_cat",
        ),
        migrations.RemoveConstraint(
            model_name="budgetmonth",
            name="trakledger_budgetmonth_unique_env_month",
        ),
        migrations.RemoveConstraint(
            model_name="budgetplan",
            name="trakledger_budgetplan_unique_code",
        ),
        migrations.RemoveConstraint(
            model_name="costcenter",
            name="trakledger_costcenter_unique_code",
        ),
        migrations.RemoveConstraint(
            model_name="costtransaction",
            name="finance_costtx_unique_idempotency",
        ),
        migrations.RemoveConstraint(
            model_name="energyreading",
            name="trakledger_ereading_unique_asset_date",
        ),
        migrations.RemoveConstraint(
            model_name="risksnapshot",
            name="trakledger_risksnapshot_unique_asset_date",
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    'ALTER INDEX IF EXISTS "finance_commit_cc_idx" RENAME TO "trakledger_commit_cc_idx";',
                    reverse_sql='ALTER INDEX IF EXISTS "trakledger_commit_cc_idx" RENAME TO "finance_commit_cc_idx";',
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name="commitment",
                    new_name="trakledger_commit_cc_idx",
                    old_name="finance_commit_cc_idx",
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    'ALTER INDEX IF EXISTS "finance_commit_month_idx" RENAME TO "trakledger_commit_month_idx";',
                    reverse_sql='ALTER INDEX IF EXISTS "trakledger_commit_month_idx" RENAME TO "finance_commit_month_idx";',
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name="commitment",
                    new_name="trakledger_commit_month_idx",
                    old_name="finance_commit_month_idx",
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    'ALTER INDEX IF EXISTS "finance_commit_status_idx" RENAME TO "trakledger_commit_status_idx";',
                    reverse_sql='ALTER INDEX IF EXISTS "trakledger_commit_status_idx" RENAME TO "finance_commit_status_idx";',
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name="commitment",
                    new_name="trakledger_commit_status_idx",
                    old_name="finance_commit_status_idx",
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    'ALTER INDEX IF EXISTS "finance_commit_cat_idx" RENAME TO "trakledger_commit_cat_idx";',
                    reverse_sql='ALTER INDEX IF EXISTS "trakledger_commit_cat_idx" RENAME TO "finance_commit_cat_idx";',
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name="commitment",
                    new_name="trakledger_commit_cat_idx",
                    old_name="finance_commit_cat_idx",
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    'ALTER INDEX IF EXISTS "finance_commit_wo_idx" RENAME TO "trakledger_commit_wo_idx";',
                    reverse_sql='ALTER INDEX IF EXISTS "trakledger_commit_wo_idx" RENAME TO "finance_commit_wo_idx";',
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name="commitment",
                    new_name="trakledger_commit_wo_idx",
                    old_name="finance_commit_wo_idx",
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    'ALTER INDEX IF EXISTS "finance_commit_summary_idx" RENAME TO "trakledger_commit_summary_idx";',
                    reverse_sql='ALTER INDEX IF EXISTS "trakledger_commit_summary_idx" RENAME TO "finance_commit_summary_idx";',
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name="commitment",
                    new_name="trakledger_commit_summary_idx",
                    old_name="finance_commit_summary_idx",
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    'ALTER INDEX IF EXISTS "finance_ctx_idemp_idx" RENAME TO "trakledger_ctx_idemp_idx";',
                    reverse_sql='ALTER INDEX IF EXISTS "trakledger_ctx_idemp_idx" RENAME TO "finance_ctx_idemp_idx";',
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name="costtransaction",
                    new_name="trakledger_ctx_idemp_idx",
                    old_name="finance_ctx_idemp_idx",
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    'ALTER INDEX IF EXISTS "finance_ctx_type_idx" RENAME TO "trakledger_ctx_type_idx";',
                    reverse_sql='ALTER INDEX IF EXISTS "trakledger_ctx_type_idx" RENAME TO "finance_ctx_type_idx";',
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name="costtransaction",
                    new_name="trakledger_ctx_type_idx",
                    old_name="finance_ctx_type_idx",
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    'ALTER INDEX IF EXISTS "finance_ctx_cat_idx" RENAME TO "trakledger_ctx_cat_idx";',
                    reverse_sql='ALTER INDEX IF EXISTS "trakledger_ctx_cat_idx" RENAME TO "finance_ctx_cat_idx";',
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name="costtransaction",
                    new_name="trakledger_ctx_cat_idx",
                    old_name="finance_ctx_cat_idx",
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    'ALTER INDEX IF EXISTS "finance_ctx_occurred_idx" RENAME TO "trakledger_ctx_occurred_idx";',
                    reverse_sql='ALTER INDEX IF EXISTS "trakledger_ctx_occurred_idx" RENAME TO "finance_ctx_occurred_idx";',
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name="costtransaction",
                    new_name="trakledger_ctx_occurred_idx",
                    old_name="finance_ctx_occurred_idx",
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    'ALTER INDEX IF EXISTS "finance_ctx_cc_idx" RENAME TO "trakledger_ctx_cc_idx";',
                    reverse_sql='ALTER INDEX IF EXISTS "trakledger_ctx_cc_idx" RENAME TO "finance_ctx_cc_idx";',
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name="costtransaction",
                    new_name="trakledger_ctx_cc_idx",
                    old_name="finance_ctx_cc_idx",
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    'ALTER INDEX IF EXISTS "finance_ctx_wo_idx" RENAME TO "trakledger_ctx_wo_idx";',
                    reverse_sql='ALTER INDEX IF EXISTS "trakledger_ctx_wo_idx" RENAME TO "finance_ctx_wo_idx";',
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name="costtransaction",
                    new_name="trakledger_ctx_wo_idx",
                    old_name="finance_ctx_wo_idx",
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    'ALTER INDEX IF EXISTS "finance_ctx_asset_idx" RENAME TO "trakledger_ctx_asset_idx";',
                    reverse_sql='ALTER INDEX IF EXISTS "trakledger_ctx_asset_idx" RENAME TO "finance_ctx_asset_idx";',
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name="costtransaction",
                    new_name="trakledger_ctx_asset_idx",
                    old_name="finance_ctx_asset_idx",
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    'ALTER INDEX IF EXISTS "finance_ctx_locked_idx" RENAME TO "trakledger_ctx_locked_idx";',
                    reverse_sql='ALTER INDEX IF EXISTS "trakledger_ctx_locked_idx" RENAME TO "finance_ctx_locked_idx";',
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name="costtransaction",
                    new_name="trakledger_ctx_locked_idx",
                    old_name="finance_ctx_locked_idx",
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    'ALTER INDEX IF EXISTS "finance_ctx_summary_idx" RENAME TO "trakledger_ctx_summary_idx";',
                    reverse_sql='ALTER INDEX IF EXISTS "trakledger_ctx_summary_idx" RENAME TO "finance_ctx_summary_idx";',
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name="costtransaction",
                    new_name="trakledger_ctx_summary_idx",
                    old_name="finance_ctx_summary_idx",
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    'ALTER INDEX IF EXISTS "finance_adj_orig_tx_idx" RENAME TO "trakledger_adj_orig_tx_idx";',
                    reverse_sql='ALTER INDEX IF EXISTS "trakledger_adj_orig_tx_idx" RENAME TO "finance_adj_orig_tx_idx";',
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name="ledgeradjustment",
                    new_name="trakledger_adj_orig_tx_idx",
                    old_name="finance_adj_orig_tx_idx",
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    'ALTER INDEX IF EXISTS "finance_adj_type_idx" RENAME TO "trakledger_adj_type_idx";',
                    reverse_sql='ALTER INDEX IF EXISTS "trakledger_adj_type_idx" RENAME TO "finance_adj_type_idx";',
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name="ledgeradjustment",
                    new_name="trakledger_adj_type_idx",
                    old_name="finance_adj_type_idx",
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    'ALTER INDEX IF EXISTS "finance_adj_created_idx" RENAME TO "trakledger_adj_created_idx";',
                    reverse_sql='ALTER INDEX IF EXISTS "trakledger_adj_created_idx" RENAME TO "finance_adj_created_idx";',
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name="ledgeradjustment",
                    new_name="trakledger_adj_created_idx",
                    old_name="finance_adj_created_idx",
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    'ALTER INDEX IF EXISTS "finance_adj_approved_idx" RENAME TO "trakledger_adj_approved_idx";',
                    reverse_sql='ALTER INDEX IF EXISTS "trakledger_adj_approved_idx" RENAME TO "finance_adj_approved_idx";',
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name="ledgeradjustment",
                    new_name="trakledger_adj_approved_idx",
                    old_name="finance_adj_approved_idx",
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    'ALTER INDEX IF EXISTS "finance_savings_cc_idx" RENAME TO "tl_savings_cc_idx";',
                    reverse_sql='ALTER INDEX IF EXISTS "tl_savings_cc_idx" RENAME TO "finance_savings_cc_idx";',
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name="savingsevent",
                    new_name="tl_savings_cc_idx",
                    old_name="finance_savings_cc_idx",
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    'ALTER INDEX IF EXISTS "finance_savings_type_idx" RENAME TO "tl_savings_type_idx";',
                    reverse_sql='ALTER INDEX IF EXISTS "tl_savings_type_idx" RENAME TO "finance_savings_type_idx";',
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name="savingsevent",
                    new_name="tl_savings_type_idx",
                    old_name="finance_savings_type_idx",
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    'ALTER INDEX IF EXISTS "finance_savings_occurred_idx" RENAME TO "tl_savings_occurred_idx";',
                    reverse_sql='ALTER INDEX IF EXISTS "tl_savings_occurred_idx" RENAME TO "finance_savings_occurred_idx";',
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name="savingsevent",
                    new_name="tl_savings_occurred_idx",
                    old_name="finance_savings_occurred_idx",
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    'ALTER INDEX IF EXISTS "finance_savings_asset_idx" RENAME TO "tl_savings_asset_idx";',
                    reverse_sql='ALTER INDEX IF EXISTS "tl_savings_asset_idx" RENAME TO "finance_savings_asset_idx";',
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name="savingsevent",
                    new_name="tl_savings_asset_idx",
                    old_name="finance_savings_asset_idx",
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    'ALTER INDEX IF EXISTS "finance_savings_wo_idx" RENAME TO "tl_savings_wo_idx";',
                    reverse_sql='ALTER INDEX IF EXISTS "tl_savings_wo_idx" RENAME TO "finance_savings_wo_idx";',
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name="savingsevent",
                    new_name="tl_savings_wo_idx",
                    old_name="finance_savings_wo_idx",
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    'ALTER INDEX IF EXISTS "finance_savings_summary_idx" RENAME TO "tl_savings_summary_idx";',
                    reverse_sql='ALTER INDEX IF EXISTS "tl_savings_summary_idx" RENAME TO "finance_savings_summary_idx";',
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name="savingsevent",
                    new_name="tl_savings_summary_idx",
                    old_name="finance_savings_summary_idx",
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    'ALTER TABLE "trakledger_budgetenvelope" DROP CONSTRAINT IF EXISTS "tl_env_uniq_plan_cc_cat"; '
                    'ALTER TABLE "trakledger_budgetenvelope" ADD CONSTRAINT "tl_env_uniq_plan_cc_cat" UNIQUE '
                    '("budget_plan_id", "cost_center_id", "category");',
                    reverse_sql='ALTER TABLE "trakledger_budgetenvelope" DROP CONSTRAINT IF EXISTS '
                    '"tl_env_uniq_plan_cc_cat";',
                ),
            ],
            state_operations=[
                migrations.AddConstraint(
                    model_name="budgetenvelope",
                    constraint=models.UniqueConstraint(
                        fields=("budget_plan", "cost_center", "category"),
                        name="tl_env_uniq_plan_cc_cat",
                    ),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    'ALTER TABLE "trakledger_budgetmonth" DROP CONSTRAINT IF EXISTS "tl_bm_uniq_env_month"; ALTER TABLE "trakledger_budgetmonth" ADD CONSTRAINT "tl_bm_uniq_env_month" UNIQUE ("envelope_id", "month");',
                    reverse_sql='ALTER TABLE "trakledger_budgetmonth" DROP CONSTRAINT IF EXISTS "tl_bm_uniq_env_month";',
                ),
            ],
            state_operations=[
                migrations.AddConstraint(
                    model_name="budgetmonth",
                    constraint=models.UniqueConstraint(
                        fields=("envelope", "month"), name="tl_bm_uniq_env_month"
                    ),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    'ALTER TABLE "trakledger_budgetplan" DROP CONSTRAINT IF EXISTS "tl_bp_unique_code"; ALTER TABLE "trakledger_budgetplan" ADD CONSTRAINT "tl_bp_unique_code" UNIQUE ("code");',
                    reverse_sql='ALTER TABLE "trakledger_budgetplan" DROP CONSTRAINT IF EXISTS "tl_bp_unique_code";',
                ),
            ],
            state_operations=[
                migrations.AddConstraint(
                    model_name="budgetplan",
                    constraint=models.UniqueConstraint(
                        fields=("code",), name="tl_bp_unique_code"
                    ),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    'ALTER TABLE "trakledger_costcenter" DROP CONSTRAINT IF EXISTS "tl_cc_unique_code"; ALTER TABLE "trakledger_costcenter" ADD CONSTRAINT "tl_cc_unique_code" UNIQUE ("code");',
                    reverse_sql='ALTER TABLE "trakledger_costcenter" DROP CONSTRAINT IF EXISTS "tl_cc_unique_code";',
                ),
            ],
            state_operations=[
                migrations.AddConstraint(
                    model_name="costcenter",
                    constraint=models.UniqueConstraint(
                        fields=("code",), name="tl_cc_unique_code"
                    ),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    'DROP INDEX IF EXISTS "tl_ctx_uniq_idempotency"; CREATE UNIQUE INDEX '
                    '"tl_ctx_uniq_idempotency" ON "trakledger_costtransaction" ("idempotency_key") '
                    'WHERE "idempotency_key" IS NOT NULL;',
                    reverse_sql='DROP INDEX IF EXISTS "tl_ctx_uniq_idempotency";',
                ),
            ],
            state_operations=[
                migrations.AddConstraint(
                    model_name="costtransaction",
                    constraint=models.UniqueConstraint(
                        condition=models.Q(("idempotency_key__isnull", False)),
                        fields=("idempotency_key",),
                        name="tl_ctx_uniq_idempotency",
                    ),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    'ALTER TABLE "trakledger_energyreading" DROP CONSTRAINT IF EXISTS "tl_eread_uniq_asset_date"; ALTER TABLE "trakledger_energyreading" ADD CONSTRAINT "tl_eread_uniq_asset_date" UNIQUE ("asset_id", "reading_date");',
                    reverse_sql='ALTER TABLE "trakledger_energyreading" DROP CONSTRAINT IF EXISTS "tl_eread_uniq_asset_date";',
                ),
            ],
            state_operations=[
                migrations.AddConstraint(
                    model_name="energyreading",
                    constraint=models.UniqueConstraint(
                        fields=("asset", "reading_date"),
                        name="tl_eread_uniq_asset_date",
                    ),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    'ALTER TABLE "trakledger_risksnapshot" DROP CONSTRAINT IF EXISTS "tl_risk_uniq_asset_date"; ALTER TABLE "trakledger_risksnapshot" ADD CONSTRAINT "tl_risk_uniq_asset_date" UNIQUE ("asset_id", "snapshot_date");',
                    reverse_sql='ALTER TABLE "trakledger_risksnapshot" DROP CONSTRAINT IF EXISTS "tl_risk_uniq_asset_date";',
                ),
            ],
            state_operations=[
                migrations.AddConstraint(
                    model_name="risksnapshot",
                    constraint=models.UniqueConstraint(
                        fields=("asset", "snapshot_date"),
                        name="tl_risk_uniq_asset_date",
                    ),
                ),
            ],
        ),
    ]
