# Generated by Django 5.0.1 on 2026-01-02 04:31

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_allow_null_category_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorycategory",
            name="code",
            field=models.CharField(
                blank=True, max_length=50, null=True, unique=True, verbose_name="Código"
            ),
        ),
        migrations.AlterField(
            model_name="inventorymovement",
            name="quantity",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Quantidade",
            ),
        ),
    ]
