# Generated by Django - FIN-003
# Migration to add cost_center to WorkOrder

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('cmms', '0007_add_cost_components'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='cost_center',
            field=models.ForeignKey(
                blank=True,
                help_text='Centro de custo para lançamentos financeiros (obrigatório para custos)',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='work_orders',
                to='finance.costcenter',
                verbose_name='Centro de Custo'
            ),
        ),
    ]
