# Generated by Django - FIN-003
# Migration to add cost_center to WorkOrder
# NOTE: Originally had dependency on finance.0001_initial which was renamed to trakledger.
# The dependency is declared here to satisfy Django's model state resolution.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cmms", "0007_add_cost_components"),
        ("trakledger", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorder",
            name="cost_center",
            field=models.ForeignKey(
                blank=True,
                help_text="Centro de custo para lançamentos financeiros (obrigatório para custos)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="work_orders",
                to="trakledger.costcenter",
                verbose_name="Centro de Custo",
            ),
        ),
    ]
