# Generated by Django 5.0.1 on 2025-12-29 02:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cmms", "0008_add_work_order_cost_center"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externalcost",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Valor total do custo",
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(0.01)],
                verbose_name="Valor",
            ),
        ),
        migrations.AlterField(
            model_name="partusage",
            name="quantity",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0.01)],
                verbose_name="Quantidade",
            ),
        ),
        migrations.AlterField(
            model_name="timeentry",
            name="hours",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Quantidade de horas trabalhadas",
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(0.01)],
                verbose_name="Horas",
            ),
        ),
    ]
