# Generated by Django 5.0.1 on 2025-12-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cmms", "0009_add_commitment_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorder",
            name="signature",
            field=models.TextField(
                blank=True,
                help_text="Assinatura do responsável em base64 (data URL da imagem)",
                verbose_name="Assinatura",
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="signed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Data/hora da assinatura",
                null=True,
                verbose_name="Assinado em",
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="signed_by",
            field=models.CharField(
                blank=True,
                help_text="Nome de quem assinou a ordem de serviço",
                max_length=255,
                verbose_name="Assinado por",
            ),
        ),
    ]
