# Generated by Django 5.0.1 on 2026-01-11 23:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cmms", "0012_change_part_usage_inventory_movement_id_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nome descritivo do relatório gerado",
                        max_length=255,
                        verbose_name="Nome do Relatório",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("PMOC_MENSAL", "PMOC Mensal"),
                            ("PMOC_ANUAL", "PMOC Anual"),
                            ("CONFORMIDADE_ANVISA", "Conformidade ANVISA"),
                            ("QUALIDADE_AR", "Qualidade do Ar Interior"),
                            ("LAUDO_TECNICO", "Laudo Técnico"),
                            ("DESEMPENHO_EQUIPAMENTOS", "Desempenho de Equipamentos"),
                            ("CONSUMO_ENERGETICO", "Consumo Energético"),
                            ("ALERTAS", "Resumo de Alertas"),
                            ("SLA", "Conformidade SLA"),
                            ("OUTROS", "Outros"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de Relatório",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "Processando"),
                            ("completed", "Concluído"),
                            ("failed", "Falhou"),
                        ],
                        default="processing",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "period_month",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Mês do período (1-12), null para relatórios anuais",
                        null=True,
                        verbose_name="Mês",
                    ),
                ),
                (
                    "period_year",
                    models.PositiveSmallIntegerField(
                        help_text="Ano do período", verbose_name="Ano"
                    ),
                ),
                (
                    "filters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Filtros aplicados na geração (company, site_id, etc)",
                        verbose_name="Filtros",
                    ),
                ),
                (
                    "content",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Dados completos do relatório em JSON",
                        verbose_name="Conteúdo",
                    ),
                ),
                (
                    "size_bytes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Tamanho (bytes)"
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="cmms/reports/%Y/%m/",
                        verbose_name="Arquivo PDF",
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Gerado em"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Concluído em"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Mensagem de Erro"),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Gerado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Relatório Gerado",
                "verbose_name_plural": "Relatórios Gerados",
                "ordering": ["-generated_at"],
                "indexes": [
                    models.Index(
                        fields=["report_type", "-generated_at"],
                        name="cmms_genera_report__8aad42_idx",
                    ),
                    models.Index(
                        fields=["status", "-generated_at"],
                        name="cmms_genera_status_ed8f76_idx",
                    ),
                    models.Index(
                        fields=["period_year", "period_month"],
                        name="cmms_genera_period__4c5496_idx",
                    ),
                ],
            },
        ),
    ]
