# Generated by Django 5.2.8 on 2026-01-12 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cmms", "0013_generated_report"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    "ALTER TABLE cmms_partusage ALTER COLUMN inventory_movement_id TYPE bigint USING NULL::bigint;",
                    reverse_sql="ALTER TABLE cmms_partusage ALTER COLUMN inventory_movement_id TYPE uuid USING NULL::uuid;",
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="partusage",
                    name="inventory_movement_id",
                    field=models.PositiveBigIntegerField(
                        blank=True,
                        help_text="Refer\u00eancia \u00e0 movimenta\u00e7\u00e3o de invent\u00e1rio",
                        null=True,
                        verbose_name="ID da Movimenta\u00e7\u00e3o",
                    ),
                ),
            ],
        ),
    ]
