# Generated by Django 5.0.1 on 2026-01-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cmms", "0014_alter_partusage_inventory_movement_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workorder",
            name="type",
            field=models.CharField(
                choices=[
                    ("PREVENTIVE", "Preventiva"),
                    ("CORRECTIVE", "Corretiva"),
                    ("PREDICTIVE", "Preditiva"),
                    ("EMERGENCY", "Emergência"),
                    ("REQUEST", "Solicitação"),
                ],
                default="CORRECTIVE",
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
    ]
