# Generated by Codex on 2025-12-30

from django.contrib.postgres.indexes import GinIndex
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0004_add_work_order_to_alert"),
    ]

    operations = [
        TrigramExtension(),
        migrations.AddIndex(
            model_name="alert",
            index=GinIndex(
                fields=["asset_tag"],
                name="alerts_alert_asset_tag_trgm",
                opclasses=["gin_trgm_ops"],
            ),
        ),
    ]
