# Generated by Django 5.1.4 on 2026-01-18 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    """
    Initial migration for AI module.
    
    Creates the AIJob model for tracking agent execution.
    """

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID do Job",
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="ID do tenant que originou o job",
                        verbose_name="Tenant ID",
                    ),
                ),
                (
                    "agent_key",
                    models.CharField(
                        db_index=True,
                        help_text="Identificador único do agente (ex: root_cause, preventive)",
                        max_length=50,
                        verbose_name="Chave do Agente",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("running", "Em Execução"),
                            ("succeeded", "Sucesso"),
                            ("failed", "Falhou"),
                            ("timeout", "Timeout"),
                            ("cancelled", "Cancelado"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "input_data",
                    models.JSONField(
                        default=dict,
                        help_text="Parâmetros de entrada para o agente",
                        verbose_name="Dados de Entrada",
                    ),
                ),
                (
                    "related_type",
                    models.CharField(
                        blank=True,
                        help_text="Tipo do objeto relacionado (ex: alert, work_order)",
                        max_length=50,
                        null=True,
                        verbose_name="Tipo Relacionado",
                    ),
                ),
                (
                    "related_id",
                    models.UUIDField(
                        blank=True,
                        help_text="ID do objeto relacionado",
                        null=True,
                        verbose_name="ID Relacionado",
                    ),
                ),
                (
                    "output_data",
                    models.JSONField(
                        blank=True,
                        help_text="Resultado da execução do agente",
                        null=True,
                        verbose_name="Dados de Saída",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Mensagem de Erro"
                    ),
                ),
                (
                    "error_details",
                    models.JSONField(
                        blank=True,
                        help_text="Stack trace e contexto adicional",
                        null=True,
                        verbose_name="Detalhes do Erro",
                    ),
                ),
                (
                    "tokens_used",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total de tokens consumidos pelo LLM",
                        verbose_name="Tokens Utilizados",
                    ),
                ),
                (
                    "execution_time_ms",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Tempo de Execução (ms)",
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Chave única para evitar duplicatas",
                        max_length=255,
                        null=True,
                        verbose_name="Chave de Idempotência",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Criado em",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Iniciado em"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completado em"
                    ),
                ),
                (
                    "attempts",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Tentativas"
                    ),
                ),
                (
                    "max_attempts",
                    models.PositiveSmallIntegerField(
                        default=3, verbose_name="Máximo de Tentativas"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_jobs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job de IA",
                "verbose_name_plural": "Jobs de IA",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="aijob",
            index=models.Index(
                fields=["tenant_id", "status"],
                name="ai_aijob_tenant__71c6f6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aijob",
            index=models.Index(
                fields=["tenant_id", "agent_key"],
                name="ai_aijob_tenant__a08c9b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aijob",
            index=models.Index(
                fields=["tenant_id", "created_at"],
                name="ai_aijob_tenant__3e7c21_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="aijob",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key__isnull", False)),
                fields=("tenant_id", "idempotency_key"),
                name="unique_ai_job_idempotency_per_tenant",
            ),
        ),
    ]
