# Generated by Django 5.0.8
"""
Migration: AIUsageLog - Token usage tracking per LLM call.

Registra métricas de uso de tokens (entrada/saída) por chamada ao LLM.
Suporta formato OpenAI compat e Ollama nativo.
"""

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0003_knowledge_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIUsageLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="ID do tenant (UUID determinístico)",
                        verbose_name="Tenant ID",
                    ),
                ),
                (
                    "tenant_schema",
                    models.CharField(
                        db_index=True,
                        help_text="Nome do schema PostgreSQL (auditoria)",
                        max_length=100,
                        verbose_name="Schema do Tenant",
                    ),
                ),
                (
                    "agent_key",
                    models.CharField(
                        db_index=True,
                        help_text="Identificador do agente (ex: preventive, predictive)",
                        max_length=50,
                        verbose_name="Chave do Agente",
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        db_index=True,
                        help_text="Modelo usado (ex: mistral-nemo, llama3)",
                        max_length=100,
                        verbose_name="Modelo LLM",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        default="openai_compat",
                        help_text="Provider LLM (openai_compat, ollama, etc)",
                        max_length=50,
                        verbose_name="Provider",
                    ),
                ),
                (
                    "input_tokens",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Mapeado de usage.prompt_tokens ou prompt_eval_count (Ollama)",
                        verbose_name="Tokens de Entrada",
                    ),
                ),
                (
                    "output_tokens",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Mapeado de usage.completion_tokens ou eval_count (Ollama)",
                        verbose_name="Tokens de Saída",
                    ),
                ),
                (
                    "total_tokens",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Se não vier, calculado como input + output",
                        verbose_name="Tokens Total",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Criado em",
                    ),
                ),
                (
                    "raw_usage",
                    models.JSONField(
                        default=dict,
                        help_text="Payload de uso bruto (tempos, métricas extras)",
                        verbose_name="Dados Brutos",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        help_text="Job relacionado (se houver)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usage_logs",
                        to="ai.aijob",
                        verbose_name="Job de IA",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_usage_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Uso de IA",
                "verbose_name_plural": "Logs de Uso de IA",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="aiusagelog",
            index=models.Index(
                fields=["tenant_id", "created_at"],
                name="ai_aiusagel_tenant__123456_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aiusagelog",
            index=models.Index(
                fields=["tenant_id", "agent_key", "created_at"],
                name="ai_aiusagel_tenant__789abc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aiusagelog",
            index=models.Index(
                fields=["tenant_id", "model", "created_at"],
                name="ai_aiusagel_tenant__def012_idx",
            ),
        ),
    ]
