# Generated by Django 5.0.1 on 2025-12-28

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration inicial para o app core_events.

    Cria a tabela OutboxEvent para o padrão Transactional Outbox.

    Referência: docs/events/01-contrato-eventos.md
    """

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="ID do Evento",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID do Evento",
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="ID do tenant que originou o evento",
                        verbose_name="Tenant ID",
                    ),
                ),
                (
                    "event_name",
                    models.CharField(
                        db_index=True,
                        help_text="Nome qualificado do evento (ex: work_order.closed, cost.entry_posted)",
                        max_length=100,
                        verbose_name="Nome do Evento",
                    ),
                ),
                (
                    "aggregate_type",
                    models.CharField(
                        help_text="Tipo do agregado de origem (ex: work_order, commitment)",
                        max_length=100,
                        verbose_name="Tipo do Agregado",
                    ),
                ),
                (
                    "aggregate_id",
                    models.UUIDField(
                        help_text="ID do agregado que originou o evento",
                        verbose_name="ID do Agregado",
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        help_text="Momento em que o evento ocorreu no domínio",
                        verbose_name="Ocorreu em",
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        help_text="Envelope completo do evento conforme contrato",
                        verbose_name="Payload",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("processed", "Processado"),
                            ("failed", "Falhou"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        help_text="Chave única para garantir processamento exatamente uma vez",
                        max_length=255,
                        verbose_name="Chave de Idempotência",
                    ),
                ),
                (
                    "attempts",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Número de tentativas de processamento",
                        verbose_name="Tentativas",
                    ),
                ),
                (
                    "max_attempts",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Número máximo de tentativas antes de marcar como failed",
                        verbose_name="Máximo de Tentativas",
                    ),
                ),
                (
                    "last_error",
                    models.TextField(
                        blank=True,
                        help_text="Mensagem do último erro de processamento",
                        null=True,
                        verbose_name="Último Erro",
                    ),
                ),
                (
                    "last_attempt_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp da última tentativa de processamento",
                        null=True,
                        verbose_name="Última Tentativa em",
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp de quando foi processado com sucesso",
                        null=True,
                        verbose_name="Processado em",
                    ),
                ),
                (
                    "processed_by",
                    models.CharField(
                        blank=True,
                        help_text="Identificador do worker/handler que processou",
                        max_length=255,
                        null=True,
                        verbose_name="Processado por",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Criado em",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name="Atualizado em",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento Outbox",
                "verbose_name_plural": "Eventos Outbox",
                "ordering": ["-created_at"],
            },
        ),
        # Índices para performance
        migrations.AddIndex(
            model_name="outboxevent",
            index=models.Index(
                fields=["tenant_id", "status", "created_at"],
                name="outbox_tenant_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="outboxevent",
            index=models.Index(
                fields=["event_name", "status"],
                name="outbox_event_name_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="outboxevent",
            index=models.Index(
                fields=["aggregate_type", "aggregate_id"],
                name="outbox_aggregate_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="outboxevent",
            index=models.Index(
                fields=["status", "created_at"],
                name="outbox_pending_idx",
            ),
        ),
        # Constraint de unicidade para idempotência por tenant
        migrations.AddConstraint(
            model_name="outboxevent",
            constraint=models.UniqueConstraint(
                fields=["tenant_id", "idempotency_key"],
                name="outbox_tenant_idempotency_unique",
            ),
        ),
    ]
