# Generated by Django 5.0.1 on 2026-01-02 04:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outboxevent",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="ID do Evento",
            ),
        ),
    ]
