# Generated by Django 5.0.1 on 2025-12-27 23:34

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nome do plano orçamentário (ex: Orçamento 2024)",
                        max_length=200,
                        verbose_name="Nome",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Código único do plano (ex: BUDGET-2024)",
                        max_length=50,
                        verbose_name="Código",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "year",
                    models.PositiveIntegerField(
                        help_text="Ano do plano orçamentário", verbose_name="Ano"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        help_text="Data de início do período do plano",
                        verbose_name="Data Início",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        help_text="Data de fim do período do plano",
                        verbose_name="Data Fim",
                    ),
                ),
                (
                    "total_planned",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Soma de todos os envelopes",
                        max_digits=15,
                        verbose_name="Total Planejado",
                    ),
                ),
                (
                    "currency",
                    models.CharField(default="BRL", max_length=3, verbose_name="Moeda"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Rascunho"),
                            ("active", "Ativo"),
                            ("closed", "Fechado"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_budget_plans",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plano Orçamentário",
                "verbose_name_plural": "Planos Orçamentários",
                "ordering": ["-year", "name"],
            },
        ),
        migrations.CreateModel(
            name="CostCenter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Código único do centro de custo (ex: CC-001)",
                        max_length=50,
                        verbose_name="Código",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nome descritivo do centro de custo",
                        max_length=200,
                        verbose_name="Nome",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Tags para classificação (ex: ["hvac", "crítico"])',
                        verbose_name="Tags",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_cost_centers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="finance.costcenter",
                        verbose_name="Centro de Custo Pai",
                    ),
                ),
            ],
            options={
                "verbose_name": "Centro de Custo",
                "verbose_name_plural": "Centros de Custo",
                "ordering": ["code", "name"],
            },
        ),
        migrations.CreateModel(
            name="BudgetEnvelope",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nome do envelope (ex: Manutenção Preventiva HVAC)",
                        max_length=200,
                        verbose_name="Nome",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("preventive", "Manutenção Preventiva"),
                            ("corrective", "Manutenção Corretiva"),
                            ("predictive", "Manutenção Preditiva"),
                            ("improvement", "Melhorias"),
                            ("contracts", "Contratos"),
                            ("parts", "Peças e Materiais"),
                            ("energy", "Energia"),
                            ("other", "Outros"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Categoria",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor total alocado para este envelope",
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Valor Total",
                    ),
                ),
                (
                    "currency",
                    models.CharField(default="BRL", max_length=3, verbose_name="Moeda"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "budget_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="envelopes",
                        to="finance.budgetplan",
                        verbose_name="Plano Orçamentário",
                    ),
                ),
                (
                    "cost_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="budget_envelopes",
                        to="finance.costcenter",
                        verbose_name="Centro de Custo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Envelope de Orçamento",
                "verbose_name_plural": "Envelopes de Orçamento",
                "ordering": ["budget_plan", "category", "name"],
            },
        ),
        migrations.CreateModel(
            name="RateCard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        help_text="Nome da função (ex: Técnico HVAC, Eletricista)",
                        max_length=100,
                        verbose_name="Função/Cargo",
                    ),
                ),
                (
                    "role_code",
                    models.CharField(
                        blank=True,
                        help_text="Código único da função (ex: TECH-HVAC)",
                        max_length=50,
                        verbose_name="Código da Função",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "cost_per_hour",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor em reais por hora trabalhada",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Custo por Hora",
                    ),
                ),
                (
                    "currency",
                    models.CharField(default="BRL", max_length=3, verbose_name="Moeda"),
                ),
                (
                    "effective_from",
                    models.DateField(
                        help_text="Data de início da vigência deste custo",
                        verbose_name="Vigência Início",
                    ),
                ),
                (
                    "effective_to",
                    models.DateField(
                        blank=True,
                        help_text="Data de fim da vigência (vazio = vigente)",
                        null=True,
                        verbose_name="Vigência Fim",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_rate_cards",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tabela de Custo",
                "verbose_name_plural": "Tabelas de Custo",
                "ordering": ["role", "-effective_from"],
            },
        ),
        migrations.CreateModel(
            name="BudgetMonth",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "month",
                    models.DateField(
                        help_text="Primeiro dia do mês (ex: 2024-01-01)",
                        verbose_name="Mês",
                    ),
                ),
                (
                    "planned_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor planejado para este mês",
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Valor Planejado",
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False,
                        help_text="Se bloqueado, não permite alterações em transações",
                        verbose_name="Período Bloqueado",
                    ),
                ),
                (
                    "locked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Bloqueado em"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "envelope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="months",
                        to="finance.budgetenvelope",
                        verbose_name="Envelope",
                    ),
                ),
                (
                    "locked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locked_budget_months",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Bloqueado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mês do Orçamento",
                "verbose_name_plural": "Meses do Orçamento",
                "ordering": ["envelope", "month"],
                "indexes": [
                    models.Index(fields=["envelope"], name="finance_bm_envelope_idx"),
                    models.Index(fields=["month"], name="finance_bm_month_idx"),
                    models.Index(fields=["is_locked"], name="finance_bm_locked_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="budgetmonth",
            constraint=models.UniqueConstraint(
                fields=("envelope", "month"),
                name="finance_budgetmonth_unique_env_month",
            ),
        ),
        migrations.AddIndex(
            model_name="budgetplan",
            index=models.Index(fields=["code"], name="finance_bp_code_idx"),
        ),
        migrations.AddIndex(
            model_name="budgetplan",
            index=models.Index(fields=["year"], name="finance_bp_year_idx"),
        ),
        migrations.AddIndex(
            model_name="budgetplan",
            index=models.Index(fields=["status"], name="finance_bp_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="budgetplan",
            constraint=models.UniqueConstraint(
                fields=("code",), name="finance_budgetplan_unique_code"
            ),
        ),
        migrations.AddIndex(
            model_name="costcenter",
            index=models.Index(fields=["code"], name="finance_cc_code_idx"),
        ),
        migrations.AddIndex(
            model_name="costcenter",
            index=models.Index(fields=["parent"], name="finance_cc_parent_idx"),
        ),
        migrations.AddIndex(
            model_name="costcenter",
            index=models.Index(fields=["is_active"], name="finance_cc_active_idx"),
        ),
        migrations.AddConstraint(
            model_name="costcenter",
            constraint=models.UniqueConstraint(
                fields=("code",), name="finance_costcenter_unique_code"
            ),
        ),
        migrations.AddIndex(
            model_name="budgetenvelope",
            index=models.Index(fields=["budget_plan"], name="finance_env_plan_idx"),
        ),
        migrations.AddIndex(
            model_name="budgetenvelope",
            index=models.Index(fields=["cost_center"], name="finance_env_cc_idx"),
        ),
        migrations.AddIndex(
            model_name="budgetenvelope",
            index=models.Index(fields=["category"], name="finance_env_cat_idx"),
        ),
        migrations.AddConstraint(
            model_name="budgetenvelope",
            constraint=models.UniqueConstraint(
                fields=("budget_plan", "cost_center", "category"),
                name="finance_envelope_unique_plan_cc_cat",
            ),
        ),
        migrations.AddIndex(
            model_name="ratecard",
            index=models.Index(fields=["role"], name="finance_rc_role_idx"),
        ),
        migrations.AddIndex(
            model_name="ratecard",
            index=models.Index(fields=["role_code"], name="finance_rc_role_code_idx"),
        ),
        migrations.AddIndex(
            model_name="ratecard",
            index=models.Index(
                fields=["effective_from", "effective_to"],
                name="finance_rc_vigencia_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ratecard",
            index=models.Index(fields=["is_active"], name="finance_rc_active_idx"),
        ),
    ]
