# Generated by Django 5.0.1 on 2025-12-29 13:59

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0004_add_work_order_to_alert"),
        ("assets", "0005_asset_sector_asset_subsection"),
        ("cmms", "0009_add_commitment_model"),
        ("finance", "0003_add_commitment_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SavingsEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("avoided_failure", "Falha Evitada"),
                            ("energy_savings", "Economia de Energia"),
                            ("optimized_maintenance", "Manutenção Otimizada"),
                            ("early_detection", "Detecção Precoce"),
                            ("reduced_downtime", "Redução de Parada"),
                            ("other", "Outros"),
                        ],
                        max_length=30,
                        verbose_name="Tipo de Evento",
                    ),
                ),
                (
                    "savings_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor estimado da economia",
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Valor Economizado",
                    ),
                ),
                (
                    "currency",
                    models.CharField(default="BRL", max_length=3, verbose_name="Moeda"),
                ),
                (
                    "confidence",
                    models.CharField(
                        choices=[
                            ("high", "Alta"),
                            ("medium", "Média"),
                            ("low", "Baixa"),
                        ],
                        default="medium",
                        help_text="Nível de confiança na estimativa",
                        max_length=10,
                        verbose_name="Confiança",
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        help_text="Data em que a economia foi identificada",
                        verbose_name="Data da Ocorrência",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Descrição detalhada do evento de economia",
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "calculation_method",
                    models.TextField(
                        blank=True,
                        help_text="Como o valor da economia foi calculado",
                        verbose_name="Metodologia de Cálculo",
                    ),
                ),
                (
                    "evidence",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Links, fotos, documentos que comprovam a economia",
                        verbose_name="Evidências",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "alert",
                    models.ForeignKey(
                        blank=True,
                        help_text="Alerta que originou a economia",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="savings_events",
                        to="alerts.alert",
                        verbose_name="Alerta",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        help_text="Ativo relacionado à economia",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="savings_events",
                        to="assets.asset",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "cost_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="savings_events",
                        to="finance.costcenter",
                        verbose_name="Centro de Custo",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_savings_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        blank=True,
                        help_text="OS que identificou/gerou a economia",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="savings_events",
                        to="cmms.workorder",
                        verbose_name="Ordem de Serviço",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento de Economia",
                "verbose_name_plural": "Eventos de Economia",
                "ordering": ["-occurred_at"],
                "indexes": [
                    models.Index(fields=["cost_center"], name="finance_savings_cc_idx"),
                    models.Index(
                        fields=["event_type"], name="finance_savings_type_idx"
                    ),
                    models.Index(
                        fields=["occurred_at"], name="finance_savings_occurred_idx"
                    ),
                    models.Index(fields=["asset"], name="finance_savings_asset_idx"),
                    models.Index(fields=["work_order"], name="finance_savings_wo_idx"),
                    models.Index(
                        fields=["cost_center", "occurred_at", "event_type"],
                        name="finance_savings_summary_idx",
                    ),
                ],
            },
        ),
    ]
