# Generated by Django 5.0.1 on 2025-12-29 23:36

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0005_add_v2_energy_baseline_risk"),
    ]

    operations = [
        migrations.AddField(
            model_name="budgetmonth",
            name="contingency_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Valor reservado para contingências neste mês",
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Valor de Contingência",
            ),
        ),
    ]
