# Generated by Django 5.0.1 on 2025-12-28 02:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_add_password_reset_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invite",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Proprietário"),
                    ("admin", "Administrador"),
                    ("operator", "Operador"),
                    ("technician", "Técnico"),
                    ("requester", "Solicitante"),
                    ("viewer", "Visualizador"),
                ],
                default="viewer",
                max_length=20,
                verbose_name="Role",
            ),
        ),
        migrations.AlterField(
            model_name="tenantmembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Proprietário"),
                    ("admin", "Administrador"),
                    ("operator", "Operador"),
                    ("technician", "Técnico"),
                    ("requester", "Solicitante"),
                    ("viewer", "Visualizador"),
                ],
                default="viewer",
                max_length=20,
                verbose_name="Role",
            ),
        ),
    ]
