# Generated by Django 5.0.1 on 2025-12-30 04:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_add_requester_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="position",
            field=models.CharField(
                blank=True,
                help_text="Cargo do usuário (ex: Eletricista, Técnico HVAC, Supervisor). Deve corresponder a uma Taxa de Mão de Obra no Finance.",
                max_length=100,
                null=True,
                verbose_name="Cargo/Posição",
            ),
        ),
    ]
