# Generated by Django 5.2.8 on 2026-01-12 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_tenantfeature"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="tenantfeature",
            new_name="tenant_feat_tenant__d3515a_idx",
            old_name="tenant_feat_tenant__6d8d5a_idx",
        ),
        migrations.RenameIndex(
            model_name="tenantfeature",
            new_name="tenant_feat_feature_8cb031_idx",
            old_name="tenant_feat_feature_b6c5e3_idx",
        ),
    ]
