# Generated by Django 5.0.1 on 2026-01-06 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0009_add_unit_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="subsection",
            name="area",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Área (m²)",
            ),
        ),
        migrations.AddField(
            model_name="subsection",
            name="hvac_units",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Unidades HVAC"
            ),
        ),
        migrations.AddField(
            model_name="subsection",
            name="occupants",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Número de Ocupantes"
            ),
        ),
    ]
