# Generated by Django 5.0.1 on 2026-01-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                ("excerpt", models.TextField()),
                ("content", models.TextField()),
                ("category", models.CharField(max_length=80)),
                (
                    "author_name",
                    models.CharField(default="Equipe ClimaTrak", max_length=120),
                ),
                ("image_url", models.URLField(blank=True)),
                ("read_time_minutes", models.PositiveIntegerField(default=5)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Blog post",
                "verbose_name_plural": "Blog posts",
                "db_table": "marketing_blog_post",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
    ]
