# Generated by Django 5.0.1 on 2026-01-08 04:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cmms", "0011_add_part_usage_source"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TechnicianProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Telefone para contato em campo",
                        max_length=20,
                        verbose_name="Telefone",
                    ),
                ),
                (
                    "skills",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de especialidades do técnico",
                        verbose_name="Habilidades",
                    ),
                ),
                (
                    "work_start_time",
                    models.TimeField(
                        default="08:00",
                        help_text="Início da janela de trabalho",
                        verbose_name="Horário de Início",
                    ),
                ),
                (
                    "work_end_time",
                    models.TimeField(
                        default="18:00",
                        help_text="Fim da janela de trabalho",
                        verbose_name="Horário de Término",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Se o técnico está disponível para atribuições",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "allow_tracking",
                    models.BooleanField(
                        default=True,
                        help_text="Se o técnico permite rastreamento GPS durante trabalho",
                        verbose_name="Permitir Rastreamento",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technician_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Técnico",
                "verbose_name_plural": "Perfis de Técnicos",
                "ordering": ["user__first_name", "user__last_name"],
            },
        ),
        migrations.CreateModel(
            name="ServiceAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateField(
                        help_text="Data prevista para o atendimento",
                        verbose_name="Data Agendada",
                    ),
                ),
                (
                    "scheduled_start",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Horário Início Previsto"
                    ),
                ),
                (
                    "scheduled_end",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Horário Fim Previsto"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Agendado"),
                            ("en_route", "A Caminho"),
                            ("on_site", "No Local"),
                            ("done", "Concluído"),
                            ("canceled", "Cancelado"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "departed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Quando o técnico saiu para o local",
                        null=True,
                        verbose_name="Saída",
                    ),
                ),
                (
                    "arrived_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Quando o técnico chegou ao local",
                        null=True,
                        verbose_name="Chegada",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Quando o atendimento foi concluído",
                        null=True,
                        verbose_name="Conclusão",
                    ),
                ),
                (
                    "canceled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Quando foi cancelado (se aplicável)",
                        null=True,
                        verbose_name="Cancelamento",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Notas sobre o agendamento ou execução",
                        verbose_name="Observações",
                    ),
                ),
                (
                    "cancellation_reason",
                    models.TextField(blank=True, verbose_name="Motivo do Cancelamento"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_assignments",
                        to="cmms.workorder",
                        verbose_name="Ordem de Serviço",
                    ),
                ),
                (
                    "technician",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="trakservice.technicianprofile",
                        verbose_name="Técnico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Atribuição de Serviço",
                "verbose_name_plural": "Atribuições de Serviço",
                "ordering": ["-scheduled_date", "-scheduled_start"],
                "indexes": [
                    models.Index(
                        fields=["scheduled_date", "technician"],
                        name="trakservice_schedul_6c962f_idx",
                    ),
                    models.Index(
                        fields=["status"], name="trakservice_status_3f944e_idx"
                    ),
                    models.Index(
                        fields=["work_order"], name="trakservice_work_or_4af955_idx"
                    ),
                ],
            },
        ),
    ]
