# Generated by Django 5.0.1 on 2026-01-08 06:45

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cmms", "0011_add_part_usage_source"),
        ("inventory", "0006_alter_inventorycategory_code_and_more"),
        ("trakservice", "0003_routing_km"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        help_text="Número único do orçamento (auto-gerado)",
                        max_length=30,
                        unique=True,
                        verbose_name="Número",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Rascunho"),
                            ("sent", "Enviado"),
                            ("approved", "Aprovado"),
                            ("rejected", "Rejeitado"),
                            ("expired", "Expirado"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "valid_until",
                    models.DateField(
                        blank=True,
                        help_text="Data limite de validade do orçamento",
                        null=True,
                        verbose_name="Válido até",
                    ),
                ),
                (
                    "subtotal_services",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Subtotal Serviços",
                    ),
                ),
                (
                    "subtotal_materials",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Subtotal Materiais",
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Desconto (%)",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Desconto (R$)",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="Total"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Observações internas sobre o orçamento",
                        verbose_name="Observações",
                    ),
                ),
                (
                    "customer_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notas visíveis no orçamento enviado ao cliente",
                        verbose_name="Observações para Cliente",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Enviado em"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Aprovado em"
                    ),
                ),
                (
                    "rejected_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Rejeitado em"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="Motivo da Rejeição"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Orçamento",
                "verbose_name_plural": "Orçamentos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuoteItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[("service", "Serviço"), ("material", "Material")],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                ("code", models.CharField(max_length=50, verbose_name="Código")),
                (
                    "description",
                    models.CharField(max_length=500, verbose_name="Descrição"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=10,
                        verbose_name="Quantidade",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        default="UN", max_length=20, verbose_name="Unidade"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Preço Unitário"
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Preço Total",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                (
                    "sequence",
                    models.PositiveIntegerField(default=0, verbose_name="Sequência"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Item do Orçamento",
                "verbose_name_plural": "Itens do Orçamento",
                "ordering": ["quote", "sequence", "item_type"],
            },
        ),
        migrations.CreateModel(
            name="ServiceCatalogItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Código único do serviço (ex: SVC-001)",
                        max_length=50,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nome do serviço (ex: Manutenção preventiva HVAC)",
                        max_length=255,
                        verbose_name="Nome",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descrição detalhada do serviço",
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "estimated_duration_minutes",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Tempo médio de execução em minutos",
                        verbose_name="Duração Estimada (min)",
                    ),
                ),
                (
                    "hourly_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Custo da hora-homem para este serviço",
                        max_digits=10,
                        verbose_name="Custo HH",
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Preço base sugerido para o serviço",
                        max_digits=10,
                        verbose_name="Preço Base",
                    ),
                ),
                (
                    "margin_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Margem de lucro padrão em percentual",
                        max_digits=5,
                        verbose_name="Margem (%)",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Categoria do serviço (ex: HVAC, Elétrica, Civil)",
                        max_length=100,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Se o serviço está disponível para uso em orçamentos",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Item do Catálogo de Serviços",
                "verbose_name_plural": "Itens do Catálogo de Serviços",
                "ordering": ["category", "name"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="dailyroute",
            name="trakservice_dailyroute_technician_date_unique",
        ),
        migrations.RemoveConstraint(
            model_name="routestop",
            name="trakservice_routestop_route_sequence_unique",
        ),
        migrations.RenameIndex(
            model_name="dailyroute",
            new_name="trakservice_route_d_91b127_idx",
            old_name="trakservice_route_date_tech_idx",
        ),
        migrations.RenameIndex(
            model_name="dailyroute",
            new_name="trakservice_status_60efa1_idx",
            old_name="trakservice_route_status_idx",
        ),
        migrations.RenameIndex(
            model_name="locationping",
            new_name="trakservice_technic_5e8b9f_idx",
            old_name="trakservice_technic_93e4c5_idx",
        ),
        migrations.RenameIndex(
            model_name="locationping",
            new_name="trakservice_recorde_0aeb2b_idx",
            old_name="trakservice_recorde_7d3f8a_idx",
        ),
        migrations.RenameIndex(
            model_name="locationping",
            new_name="trakservice_device__48f272_idx",
            old_name="trakservice_device__8a2b1c_idx",
        ),
        migrations.RenameIndex(
            model_name="routestop",
            new_name="trakservice_route_i_5ef598_idx",
            old_name="trakservice_stop_route_seq_idx",
        ),
        migrations.AlterField(
            model_name="technicianprofile",
            name="work_end_time",
            field=models.TimeField(
                default=datetime.time(18, 0),
                help_text="Fim da janela de trabalho",
                verbose_name="Horário de Término",
            ),
        ),
        migrations.AlterField(
            model_name="technicianprofile",
            name="work_start_time",
            field=models.TimeField(
                default=datetime.time(8, 0),
                help_text="Início da janela de trabalho",
                verbose_name="Horário de Início",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailyroute",
            unique_together={("technician", "route_date")},
        ),
        migrations.AlterUniqueTogether(
            name="routestop",
            unique_together={("route", "sequence")},
        ),
        migrations.AddField(
            model_name="quote",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_quotes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Aprovado por",
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_quotes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criado por",
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="work_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quotes",
                to="cmms.workorder",
                verbose_name="Ordem de Serviço",
            ),
        ),
        migrations.AddField(
            model_name="quoteitem",
            name="inventory_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quote_items",
                to="inventory.inventoryitem",
                verbose_name="Item do Estoque",
            ),
        ),
        migrations.AddField(
            model_name="quoteitem",
            name="quote",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="trakservice.quote",
                verbose_name="Orçamento",
            ),
        ),
        migrations.AddField(
            model_name="servicecatalogitem",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_catalog_items",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criado por",
            ),
        ),
        migrations.AddField(
            model_name="quoteitem",
            name="catalog_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quote_items",
                to="trakservice.servicecatalogitem",
                verbose_name="Item do Catálogo",
            ),
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(fields=["number"], name="trakservice_number_2c6c24_idx"),
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(
                fields=["work_order", "status"], name="trakservice_work_or_fba247_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(fields=["status"], name="trakservice_status_db310e_idx"),
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(
                fields=["-created_at"], name="trakservice_created_dbf893_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicecatalogitem",
            index=models.Index(fields=["code"], name="trakservice_code_861e26_idx"),
        ),
        migrations.AddIndex(
            model_name="servicecatalogitem",
            index=models.Index(
                fields=["category"], name="trakservice_categor_372f2f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicecatalogitem",
            index=models.Index(
                fields=["is_active"], name="trakservice_is_acti_1e1116_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quoteitem",
            index=models.Index(
                fields=["quote", "item_type"], name="trakservice_quote_i_794570_idx"
            ),
        ),
    ]
