# Generated by Django 5.0.1 on 2025-12-28 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantInvite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email address to invite",
                        max_length=254,
                        verbose_name="Email",
                    ),
                ),
                (
                    "email_hash",
                    models.CharField(
                        db_index=True,
                        help_text="HMAC hash for lookups",
                        max_length=64,
                        verbose_name="Email Hash",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Proprietário"),
                            ("admin", "Administrador"),
                            ("operator", "Operador"),
                            ("technician", "Técnico"),
                            ("requester", "Solicitante"),
                            ("viewer", "Visualizador"),
                        ],
                        default="viewer",
                        max_length=20,
                        verbose_name="Role",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        help_text="Unique token for invite URL",
                        max_length=64,
                        unique=True,
                        verbose_name="Token",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("accepted", "Aceito"),
                            ("expired", "Expirado"),
                            ("revoked", "Revogado"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "invited_by_email_hash",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="Invited By (Email Hash)",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Optional message to invitee",
                        verbose_name="Message",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Expires At")),
                (
                    "accepted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Accepted At"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_invites",
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant Invite",
                "verbose_name_plural": "Tenant Invites",
                "db_table": "public_tenant_invites",
                "indexes": [
                    models.Index(fields=["token"], name="public_tena_token_03fd8f_idx"),
                    models.Index(
                        fields=["email_hash", "status"],
                        name="public_tena_email_h_656e93_idx",
                    ),
                    models.Index(
                        fields=["tenant", "status"],
                        name="public_tena_tenant__5991c5_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TenantMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_hash",
                    models.CharField(
                        db_index=True,
                        help_text="HMAC-SHA256 hash of user email for lookups",
                        max_length=64,
                        verbose_name="Email Hash",
                    ),
                ),
                (
                    "tenant_user_id",
                    models.PositiveIntegerField(
                        help_text="User ID in the tenant schema (not a FK due to cross-schema)",
                        verbose_name="Tenant User ID",
                    ),
                ),
                (
                    "email_hint",
                    models.CharField(
                        blank=True,
                        help_text="Domain part of email for debugging (e.g., @company.com)",
                        max_length=100,
                        verbose_name="Email Hint",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        help_text="Cached user display name",
                        max_length=255,
                        verbose_name="Display Name",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Proprietário"),
                            ("admin", "Administrador"),
                            ("operator", "Operador"),
                            ("technician", "Técnico"),
                            ("requester", "Solicitante"),
                            ("viewer", "Visualizador"),
                        ],
                        default="viewer",
                        max_length=20,
                        verbose_name="Role",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Ativo"),
                            ("inactive", "Inativo"),
                            ("suspended", "Suspenso"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "invited_by_email_hash",
                    models.CharField(
                        blank=True,
                        help_text="Email hash of user who sent the invite",
                        max_length=64,
                        null=True,
                        verbose_name="Invited By (Email Hash)",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Joined At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_memberships",
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant Membership",
                "verbose_name_plural": "Tenant Memberships",
                "db_table": "public_tenant_memberships",
                "ordering": ["-joined_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "role", "status"],
                        name="public_tena_tenant__32d15f_idx",
                    ),
                    models.Index(
                        fields=["email_hash", "status"],
                        name="public_tena_email_h_0f4ee8_idx",
                    ),
                    models.Index(
                        fields=["tenant_user_id", "tenant"],
                        name="public_tena_tenant__6bc516_idx",
                    ),
                ],
                "unique_together": {("email_hash", "tenant")},
            },
        ),
        migrations.CreateModel(
            name="TenantUserIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier_hash",
                    models.CharField(
                        db_index=True,
                        help_text="HMAC-SHA256 hash of the user email",
                        max_length=64,
                        verbose_name="Identifier Hash",
                    ),
                ),
                (
                    "email_hint",
                    models.CharField(
                        blank=True,
                        help_text="Domain part of email for debugging (e.g., @company.com)",
                        max_length=100,
                        null=True,
                        verbose_name="Email Hint",
                    ),
                ),
                (
                    "tenant_user_id",
                    models.PositiveIntegerField(
                        help_text="User ID in the tenant schema (not a FK due to cross-schema)",
                        verbose_name="Tenant User ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this index entry is active",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_index_entries",
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant User Index",
                "verbose_name_plural": "Tenant User Index Entries",
                "db_table": "public_tenant_user_index",
                "indexes": [
                    models.Index(
                        fields=["identifier_hash", "is_active"],
                        name="public_tena_identif_c673f9_idx",
                    ),
                    models.Index(
                        fields=["tenant", "is_active"],
                        name="public_tena_tenant__3ceb62_idx",
                    ),
                ],
                "unique_together": {("identifier_hash", "tenant")},
            },
        ),
    ]
