# Generated by Django 5.0.1 on 2025-12-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_identity", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="tenantmembership",
            name="public_tena_tenant__6bc516_idx",
        ),
        migrations.AlterField(
            model_name="tenantmembership",
            name="display_name",
            field=models.CharField(
                blank=True,
                help_text="DEPRECATED - Cached user display name",
                max_length=255,
                verbose_name="Display Name (deprecated)",
            ),
        ),
        migrations.AlterField(
            model_name="tenantmembership",
            name="email_hint",
            field=models.CharField(
                blank=True,
                help_text="DEPRECATED - Domain part of email",
                max_length=100,
                verbose_name="Email Hint (deprecated)",
            ),
        ),
        migrations.AlterField(
            model_name="tenantmembership",
            name="tenant_user_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="DEPRECATED - User ID in the tenant schema",
                null=True,
                verbose_name="Tenant User ID (deprecated)",
            ),
        ),
        migrations.AlterField(
            model_name="tenantuserindex",
            name="email_hint",
            field=models.CharField(
                blank=True,
                help_text="DEPRECATED - Domain part of email",
                max_length=100,
                null=True,
                verbose_name="Email Hint (deprecated)",
            ),
        ),
        migrations.AlterField(
            model_name="tenantuserindex",
            name="tenant_user_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="DEPRECATED - User ID in tenant schema",
                null=True,
                verbose_name="Tenant User ID (deprecated)",
            ),
        ),
    ]
